[build]
builder = "NIXPACKS"
buildCommand = "yarn build"

[deploy]
startCommand = "yarn start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[services]]
name = "medusa"
port = 9000

[envs]
PORT = "9000"
NODE_ENV = "production"